services:
    wledger:
        image: tuxedomakes/wledger:latest
        container_name: wledger
        restart: always
        ports:
            - "7483:3000"
    volumes:
    # IMPORTANT:
    # Change ./wledger_data to the directory where
    # you want to store your DB, img, and upload data
        - ./wledger_data:/app/data 

volumes:
    wledger_data: