// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AuditDetailModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"audit-detail-content\" class=\"space-y-6\"><div class=\"grid grid-cols-1 lg:grid-cols-2 gap-4\"><div class=\"space-y-2\"><h4 class=\"text-xs font-bold uppercase opacity-50 flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-error\"></div>Old Value</h4><div class=\"relative group\"><pre id=\"audit-detail-old\" class=\"bg-base-200 p-4 rounded-lg overflow-x-auto text-[10px] font-mono min-h-[200px] border border-base-300\"></pre><button class=\"btn btn-xs btn-ghost absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity\" onclick=\"copyToClipboard('audit-detail-old')\">Copy</button></div></div><div class=\"space-y-2\"><h4 class=\"text-xs font-bold uppercase opacity-50 flex items-center gap-2\"><div class=\"w-2 h-2 rounded-full bg-success\"></div>New Value</h4><div class=\"relative group\"><pre id=\"audit-detail-new\" class=\"bg-base-200 p-4 rounded-lg overflow-x-auto text-[10px] font-mono min-h-[200px] border border-base-300\"></pre><button class=\"btn btn-xs btn-ghost absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity\" onclick=\"copyToClipboard('audit-detail-new')\">Copy</button></div></div></div></div><div class=\"modal-action\"><button class=\"btn btn-ghost\" onclick=\"audit_detail_modal.close()\">Close</button></div><script src=\"/static/js/audit.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Modal(ModalProps{
			ID:       "audit_detail_modal",
			Title:    "Audit Log Detail",
			BoxClass: "max-w-5xl",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
