// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/tuxedocurly/wledger/web/icons"

func BackupRestore() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card bg-base-200 shadow-xl border border-base-300\"><div class=\"card-body\"><h3 class=\"font-bold text-sm uppercase tracking-wider opacity-50 mb-4 flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.File(templ.Attributes{"class": "w-5 h-5"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "Backup & Restore</h3><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><!-- Backup Section --><div class=\"bg-base-100 p-4 rounded-lg border border-base-300 flex flex-col justify-between\"><div><h4 class=\"font-bold text-lg\">Create Backup</h4><p class=\"text-sm opacity-70 mt-1\">Download a ZIP archive containing your entire database and all uploaded assets (images, documents).</p></div><a href=\"/settings/backup/download\" class=\"btn btn-primary mt-4 gap-2\" download>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Import(templ.Attributes{"class": "w-5 h-5"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "Download</a></div><!-- Restore Section --><div class=\"bg-base-100 p-4 rounded-lg border border-base-300 flex flex-col justify-between\"><div><h4 class=\"font-bold text-lg text-error\">Restore Backup</h4><p class=\"text-sm opacity-70 mt-1\">Overwrite your current system with a backup file.  <span class=\"font-bold text-error\">This is destructive and cannot be undone.</span></p></div><button onclick=\"restore_modal.showModal()\" class=\"btn btn-outline btn-error mt-4 gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.RefreshCcw(templ.Attributes{"class": "w-5 h-5"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "Restore</button></div></div></div></div><!-- Restore Modal --><dialog id=\"restore_modal\" class=\"modal\"><div class=\"modal-box bg-base-100 border-2 border-error\"><form method=\"dialog\"><button class=\"btn btn-sm btn-circle btn-ghost absolute right-2 top-2\">✕</button></form><h3 class=\"font-bold text-xl text-error mb-4 flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.TriangleAlert(templ.Attributes{"class": "w-5 h-5"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "Danger Zone: System Restore")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.TriangleAlert(templ.Attributes{"class": "w-5 h-5"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h3><div class=\"alert alert-error text-sm\"><span>You are about to completely wipe the current database and replace it with the backup. All current parts, bins, users, and settings will be lost.</span></div><form hx-post=\"/settings/backup/restore\" hx-encoding=\"multipart/form-data\" hx-target=\"#restore_result\" hx-swap=\"innerHTML\" class=\"mt-6 space-y-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text font-medium\">Select Backup File</span> <span class=\"label-text-alt\">.zip</span></label> <input type=\"file\" name=\"backup_file\" accept=\".zip\" class=\"file-input file-input-bordered file-input-error w-full\" required></div><div class=\"form-control\"><label class=\"label cursor-pointer justify-start gap-4\"><input type=\"checkbox\" required class=\"checkbox checkbox-error\"> <span class=\"label-text text-xs\">I understand that this action is irreversible.</span></label></div><button type=\"submit\" class=\"btn btn-error w-full\">PERFORM FULL RESTORE</button></form><div id=\"restore_result\" class=\"mt-4\"></div></div><form method=\"dialog\" class=\"modal-backdrop\"><button>close</button></form></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
