// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BinPickerGrid(ctrl DashboardController) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ selectedBinID: '' }\" @bin-selected.stop=\"selectedBinID = $event.detail.id; $dispatch('bin-selected-form', {id: $event.detail.id})\" class=\"space-y-8\"><input type=\"hidden\" name=\"bin_id\" :value=\"selectedBinID\" required> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(ctrl.Containers) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"text-center py-12 opacity-50 border-2 border-dashed border-base-300 rounded-xl\"><p class=\"text-lg font-medium\">No containers configured</p><p class=\"text-sm\">This controller has no containers or mapped bins.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"grid grid-cols-1 gap-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, container := range ctrl.Containers {
				templ_7745c5c3_Err = BinPickerCard(container).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><!-- Legend --> <div class=\"flex flex-wrap justify-center gap-4 mt-4 pt-6 border-t border-base-300\"><div class=\"flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider opacity-60\"><div class=\"w-3 h-3 rounded-md bg-success\"></div>OK</div><div class=\"flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider opacity-60\"><div class=\"w-3 h-3 rounded-md bg-warning\"></div>Low</div><div class=\"flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider opacity-60\"><div class=\"w-3 h-3 rounded-md bg-error\"></div>Critical</div><div class=\"flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider opacity-60\"><div class=\"w-3 h-3 rounded-md bg-base-200 border border-base-300\"></div>Empty</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
