// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bins.sql

package db

import (
	"context"
	"database/sql"
)

const clearContainerBinLedIndices = `-- name: ClearContainerBinLedIndices :exec
UPDATE bins
SET led_index = NULL
WHERE container_id = ?
`

func (q *Queries) ClearContainerBinLedIndices(ctx context.Context, containerID int64) error {
	_, err := q.exec(ctx, q.clearContainerBinLedIndicesStmt, clearContainerBinLedIndices, containerID)
	return err
}

const createBin = `-- name: CreateBin :one
INSERT INTO bins (name, container_id, led_index, width, grid_x, grid_y)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateBinParams struct {
	Name        string        `json:"name"`
	ContainerID int64         `json:"container_id"`
	LedIndex    sql.NullInt64 `json:"led_index"`
	Width       sql.NullInt64 `json:"width"`
	GridX       sql.NullInt64 `json:"grid_x"`
	GridY       sql.NullInt64 `json:"grid_y"`
}

func (q *Queries) CreateBin(ctx context.Context, arg CreateBinParams) (int64, error) {
	row := q.queryRow(ctx, q.createBinStmt, createBin,
		arg.Name,
		arg.ContainerID,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBin = `-- name: DeleteBin :exec
DELETE FROM bins WHERE id = ?
`

func (q *Queries) DeleteBin(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteBinStmt, deleteBin, id)
	return err
}

const deleteBinByLed = `-- name: DeleteBinByLed :exec
DELETE FROM bins 
WHERE container_id = ? AND led_index = ?
`

type DeleteBinByLedParams struct {
	ContainerID int64         `json:"container_id"`
	LedIndex    sql.NullInt64 `json:"led_index"`
}

func (q *Queries) DeleteBinByLed(ctx context.Context, arg DeleteBinByLedParams) error {
	_, err := q.exec(ctx, q.deleteBinByLedStmt, deleteBinByLed, arg.ContainerID, arg.LedIndex)
	return err
}

const deleteBinsByContainer = `-- name: DeleteBinsByContainer :exec
DELETE FROM bins WHERE container_id = ?
`

func (q *Queries) DeleteBinsByContainer(ctx context.Context, containerID int64) error {
	_, err := q.exec(ctx, q.deleteBinsByContainerStmt, deleteBinsByContainer, containerID)
	return err
}

const getAllBins = `-- name: GetAllBins :many
SELECT id, name, container_id, led_index, width, grid_x, grid_y FROM bins ORDER BY id
`

func (q *Queries) GetAllBins(ctx context.Context) ([]Bin, error) {
	rows, err := q.query(ctx, q.getAllBinsStmt, getAllBins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bin
	for rows.Next() {
		var i Bin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContainerID,
			&i.LedIndex,
			&i.Width,
			&i.GridX,
			&i.GridY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBin = `-- name: GetBin :one
SELECT id, name, container_id, led_index, width, grid_x, grid_y FROM bins WHERE id = ?
`

func (q *Queries) GetBin(ctx context.Context, id int64) (Bin, error) {
	row := q.queryRow(ctx, q.getBinStmt, getBin, id)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainerID,
		&i.LedIndex,
		&i.Width,
		&i.GridX,
		&i.GridY,
	)
	return i, err
}

const getBinByLocation = `-- name: GetBinByLocation :one
SELECT b.id 
FROM bins b
JOIN containers c ON b.container_id = c.id
JOIN controllers ct ON c.controller_id = ct.id
WHERE ct.ip_address = ? AND c.segment_id = ? AND b.led_index = ?
`

type GetBinByLocationParams struct {
	IpAddress string        `json:"ip_address"`
	SegmentID int64         `json:"segment_id"`
	LedIndex  sql.NullInt64 `json:"led_index"`
}

func (q *Queries) GetBinByLocation(ctx context.Context, arg GetBinByLocationParams) (int64, error) {
	row := q.queryRow(ctx, q.getBinByLocationStmt, getBinByLocation, arg.IpAddress, arg.SegmentID, arg.LedIndex)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBinsByContainer = `-- name: GetBinsByContainer :many
SELECT id, name, container_id, led_index, width, grid_x, grid_y FROM bins 
WHERE container_id = ? 
ORDER BY led_index ASC
`

func (q *Queries) GetBinsByContainer(ctx context.Context, containerID int64) ([]Bin, error) {
	rows, err := q.query(ctx, q.getBinsByContainerStmt, getBinsByContainer, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bin
	for rows.Next() {
		var i Bin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContainerID,
			&i.LedIndex,
			&i.Width,
			&i.GridX,
			&i.GridY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreBin = `-- name: RestoreBin :exec
INSERT INTO bins (id, name, container_id, led_index, width, grid_x, grid_y)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type RestoreBinParams struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	ContainerID int64         `json:"container_id"`
	LedIndex    sql.NullInt64 `json:"led_index"`
	Width       sql.NullInt64 `json:"width"`
	GridX       sql.NullInt64 `json:"grid_x"`
	GridY       sql.NullInt64 `json:"grid_y"`
}

func (q *Queries) RestoreBin(ctx context.Context, arg RestoreBinParams) error {
	_, err := q.exec(ctx, q.restoreBinStmt, restoreBin,
		arg.ID,
		arg.Name,
		arg.ContainerID,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
	)
	return err
}

const updateBin = `-- name: UpdateBin :exec
UPDATE bins
SET name = ?, led_index = ?, width = ?, grid_x = ?, grid_y = ?
WHERE id = ?
`

type UpdateBinParams struct {
	Name     string        `json:"name"`
	LedIndex sql.NullInt64 `json:"led_index"`
	Width    sql.NullInt64 `json:"width"`
	GridX    sql.NullInt64 `json:"grid_x"`
	GridY    sql.NullInt64 `json:"grid_y"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateBin(ctx context.Context, arg UpdateBinParams) error {
	_, err := q.exec(ctx, q.updateBinStmt, updateBin,
		arg.Name,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
		arg.ID,
	)
	return err
}

const updateBinLedIndex = `-- name: UpdateBinLedIndex :exec
UPDATE bins
SET led_index = ?
WHERE id = ?
`

type UpdateBinLedIndexParams struct {
	LedIndex sql.NullInt64 `json:"led_index"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateBinLedIndex(ctx context.Context, arg UpdateBinLedIndexParams) error {
	_, err := q.exec(ctx, q.updateBinLedIndexStmt, updateBinLedIndex, arg.LedIndex, arg.ID)
	return err
}

const upsertBin = `-- name: UpsertBin :exec
INSERT INTO bins (name, container_id, led_index, width, grid_x, grid_y)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(container_id, led_index) DO UPDATE SET
    name = excluded.name,
    width = excluded.width,
    grid_x = excluded.grid_x,
    grid_y = excluded.grid_y
`

type UpsertBinParams struct {
	Name        string        `json:"name"`
	ContainerID int64         `json:"container_id"`
	LedIndex    sql.NullInt64 `json:"led_index"`
	Width       sql.NullInt64 `json:"width"`
	GridX       sql.NullInt64 `json:"grid_x"`
	GridY       sql.NullInt64 `json:"grid_y"`
}

func (q *Queries) UpsertBin(ctx context.Context, arg UpsertBinParams) error {
	_, err := q.exec(ctx, q.upsertBinStmt, upsertBin,
		arg.Name,
		arg.ContainerID,
		arg.LedIndex,
		arg.Width,
		arg.GridX,
		arg.GridY,
	)
	return err
}
