// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addContainerToWallStmt, err = db.PrepareContext(ctx, addContainerToWall); err != nil {
		return nil, fmt.Errorf("error preparing query AddContainerToWall: %w", err)
	}
	if q.addTagToPartStmt, err = db.PrepareContext(ctx, addTagToPart); err != nil {
		return nil, fmt.Errorf("error preparing query AddTagToPart: %w", err)
	}
	if q.cleanupSessionsStmt, err = db.PrepareContext(ctx, cleanupSessions); err != nil {
		return nil, fmt.Errorf("error preparing query CleanupSessions: %w", err)
	}
	if q.clearAuditLogsStmt, err = db.PrepareContext(ctx, clearAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ClearAuditLogs: %w", err)
	}
	if q.clearBinsStmt, err = db.PrepareContext(ctx, clearBins); err != nil {
		return nil, fmt.Errorf("error preparing query ClearBins: %w", err)
	}
	if q.clearContainerBinLedIndicesStmt, err = db.PrepareContext(ctx, clearContainerBinLedIndices); err != nil {
		return nil, fmt.Errorf("error preparing query ClearContainerBinLedIndices: %w", err)
	}
	if q.clearContainersStmt, err = db.PrepareContext(ctx, clearContainers); err != nil {
		return nil, fmt.Errorf("error preparing query ClearContainers: %w", err)
	}
	if q.clearControllersStmt, err = db.PrepareContext(ctx, clearControllers); err != nil {
		return nil, fmt.Errorf("error preparing query ClearControllers: %w", err)
	}
	if q.clearPartAiPromptsStmt, err = db.PrepareContext(ctx, clearPartAiPrompts); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPartAiPrompts: %w", err)
	}
	if q.clearPartAssignmentsStmt, err = db.PrepareContext(ctx, clearPartAssignments); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPartAssignments: %w", err)
	}
	if q.clearPartDocsStmt, err = db.PrepareContext(ctx, clearPartDocs); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPartDocs: %w", err)
	}
	if q.clearPartLinksStmt, err = db.PrepareContext(ctx, clearPartLinks); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPartLinks: %w", err)
	}
	if q.clearPartTagsStmt, err = db.PrepareContext(ctx, clearPartTags); err != nil {
		return nil, fmt.Errorf("error preparing query ClearPartTags: %w", err)
	}
	if q.clearPartsStmt, err = db.PrepareContext(ctx, clearParts); err != nil {
		return nil, fmt.Errorf("error preparing query ClearParts: %w", err)
	}
	if q.clearTagsStmt, err = db.PrepareContext(ctx, clearTags); err != nil {
		return nil, fmt.Errorf("error preparing query ClearTags: %w", err)
	}
	if q.clearUsersStmt, err = db.PrepareContext(ctx, clearUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ClearUsers: %w", err)
	}
	if q.clearWallCardsStmt, err = db.PrepareContext(ctx, clearWallCards); err != nil {
		return nil, fmt.Errorf("error preparing query ClearWallCards: %w", err)
	}
	if q.clearWallsStmt, err = db.PrepareContext(ctx, clearWalls); err != nil {
		return nil, fmt.Errorf("error preparing query ClearWalls: %w", err)
	}
	if q.countAuditLogsStmt, err = db.PrepareContext(ctx, countAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountAuditLogs: %w", err)
	}
	if q.countUsersStmt, err = db.PrepareContext(ctx, countUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountUsers: %w", err)
	}
	if q.createAuditLogStmt, err = db.PrepareContext(ctx, createAuditLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuditLog: %w", err)
	}
	if q.createBinStmt, err = db.PrepareContext(ctx, createBin); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBin: %w", err)
	}
	if q.createContainerStmt, err = db.PrepareContext(ctx, createContainer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContainer: %w", err)
	}
	if q.createControllerStmt, err = db.PrepareContext(ctx, createController); err != nil {
		return nil, fmt.Errorf("error preparing query CreateController: %w", err)
	}
	if q.createInspirationTemplateStmt, err = db.PrepareContext(ctx, createInspirationTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInspirationTemplate: %w", err)
	}
	if q.createPartStmt, err = db.PrepareContext(ctx, createPart); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePart: %w", err)
	}
	if q.createPartAssignmentStmt, err = db.PrepareContext(ctx, createPartAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePartAssignment: %w", err)
	}
	if q.createPartDocStmt, err = db.PrepareContext(ctx, createPartDoc); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePartDoc: %w", err)
	}
	if q.createPartLinkStmt, err = db.PrepareContext(ctx, createPartLink); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePartLink: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createTagStmt, err = db.PrepareContext(ctx, createTag); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTag: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createWallStmt, err = db.PrepareContext(ctx, createWall); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWall: %w", err)
	}
	if q.deleteAssignmentStmt, err = db.PrepareContext(ctx, deleteAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAssignment: %w", err)
	}
	if q.deleteBinStmt, err = db.PrepareContext(ctx, deleteBin); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBin: %w", err)
	}
	if q.deleteBinByLedStmt, err = db.PrepareContext(ctx, deleteBinByLed); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBinByLed: %w", err)
	}
	if q.deleteBinsByContainerStmt, err = db.PrepareContext(ctx, deleteBinsByContainer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBinsByContainer: %w", err)
	}
	if q.deleteContainerStmt, err = db.PrepareContext(ctx, deleteContainer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteContainer: %w", err)
	}
	if q.deleteControllerStmt, err = db.PrepareContext(ctx, deleteController); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteController: %w", err)
	}
	if q.deleteInspirationTemplateStmt, err = db.PrepareContext(ctx, deleteInspirationTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInspirationTemplate: %w", err)
	}
	if q.deletePartStmt, err = db.PrepareContext(ctx, deletePart); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePart: %w", err)
	}
	if q.deletePartAssignmentStmt, err = db.PrepareContext(ctx, deletePartAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePartAssignment: %w", err)
	}
	if q.deletePartDocStmt, err = db.PrepareContext(ctx, deletePartDoc); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePartDoc: %w", err)
	}
	if q.deletePartLinkStmt, err = db.PrepareContext(ctx, deletePartLink); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePartLink: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteUnusedTagsStmt, err = db.PrepareContext(ctx, deleteUnusedTags); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUnusedTags: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteWallStmt, err = db.PrepareContext(ctx, deleteWall); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWall: %w", err)
	}
	if q.deleteWallCardsByWallIDStmt, err = db.PrepareContext(ctx, deleteWallCardsByWallID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWallCardsByWallID: %w", err)
	}
	if q.getAllAuditLogsStmt, err = db.PrepareContext(ctx, getAllAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllAuditLogs: %w", err)
	}
	if q.getAllBinsStmt, err = db.PrepareContext(ctx, getAllBins); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllBins: %w", err)
	}
	if q.getAllContainersStmt, err = db.PrepareContext(ctx, getAllContainers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllContainers: %w", err)
	}
	if q.getAllInspirationTemplatesStmt, err = db.PrepareContext(ctx, getAllInspirationTemplates); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllInspirationTemplates: %w", err)
	}
	if q.getAllPartAiPromptsStmt, err = db.PrepareContext(ctx, getAllPartAiPrompts); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartAiPrompts: %w", err)
	}
	if q.getAllPartAssignmentsStmt, err = db.PrepareContext(ctx, getAllPartAssignments); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartAssignments: %w", err)
	}
	if q.getAllPartDocsStmt, err = db.PrepareContext(ctx, getAllPartDocs); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartDocs: %w", err)
	}
	if q.getAllPartLinksStmt, err = db.PrepareContext(ctx, getAllPartLinks); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartLinks: %w", err)
	}
	if q.getAllPartTagsStmt, err = db.PrepareContext(ctx, getAllPartTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartTags: %w", err)
	}
	if q.getAllPartsStmt, err = db.PrepareContext(ctx, getAllParts); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllParts: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getAllWallCardsStmt, err = db.PrepareContext(ctx, getAllWallCards); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllWallCards: %w", err)
	}
	if q.getAllWallContainerBinsStmt, err = db.PrepareContext(ctx, getAllWallContainerBins); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllWallContainerBins: %w", err)
	}
	if q.getAssignmentStmt, err = db.PrepareContext(ctx, getAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignment: %w", err)
	}
	if q.getAssignmentIDStmt, err = db.PrepareContext(ctx, getAssignmentID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignmentID: %w", err)
	}
	if q.getBinStmt, err = db.PrepareContext(ctx, getBin); err != nil {
		return nil, fmt.Errorf("error preparing query GetBin: %w", err)
	}
	if q.getBinByLocationStmt, err = db.PrepareContext(ctx, getBinByLocation); err != nil {
		return nil, fmt.Errorf("error preparing query GetBinByLocation: %w", err)
	}
	if q.getBinsByContainerStmt, err = db.PrepareContext(ctx, getBinsByContainer); err != nil {
		return nil, fmt.Errorf("error preparing query GetBinsByContainer: %w", err)
	}
	if q.getContainerStmt, err = db.PrepareContext(ctx, getContainer); err != nil {
		return nil, fmt.Errorf("error preparing query GetContainer: %w", err)
	}
	if q.getContainersByControllerStmt, err = db.PrepareContext(ctx, getContainersByController); err != nil {
		return nil, fmt.Errorf("error preparing query GetContainersByController: %w", err)
	}
	if q.getControllerStmt, err = db.PrepareContext(ctx, getController); err != nil {
		return nil, fmt.Errorf("error preparing query GetController: %w", err)
	}
	if q.getControllersStmt, err = db.PrepareContext(ctx, getControllers); err != nil {
		return nil, fmt.Errorf("error preparing query GetControllers: %w", err)
	}
	if q.getDashboardGridStmt, err = db.PrepareContext(ctx, getDashboardGrid); err != nil {
		return nil, fmt.Errorf("error preparing query GetDashboardGrid: %w", err)
	}
	if q.getDashboardGridByControllerStmt, err = db.PrepareContext(ctx, getDashboardGridByController); err != nil {
		return nil, fmt.Errorf("error preparing query GetDashboardGridByController: %w", err)
	}
	if q.getDashboardStatsStmt, err = db.PrepareContext(ctx, getDashboardStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetDashboardStats: %w", err)
	}
	if q.getFlagStmt, err = db.PrepareContext(ctx, getFlag); err != nil {
		return nil, fmt.Errorf("error preparing query GetFlag: %w", err)
	}
	if q.getInspirationTemplateStmt, err = db.PrepareContext(ctx, getInspirationTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query GetInspirationTemplate: %w", err)
	}
	if q.getPartStmt, err = db.PrepareContext(ctx, getPart); err != nil {
		return nil, fmt.Errorf("error preparing query GetPart: %w", err)
	}
	if q.getPartAssignmentsStmt, err = db.PrepareContext(ctx, getPartAssignments); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartAssignments: %w", err)
	}
	if q.getPartDocStmt, err = db.PrepareContext(ctx, getPartDoc); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartDoc: %w", err)
	}
	if q.getPartDocsStmt, err = db.PrepareContext(ctx, getPartDocs); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartDocs: %w", err)
	}
	if q.getPartLinksStmt, err = db.PrepareContext(ctx, getPartLinks); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartLinks: %w", err)
	}
	if q.getPartsForInspirationAllStmt, err = db.PrepareContext(ctx, getPartsForInspirationAll); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartsForInspirationAll: %w", err)
	}
	if q.getPartsForInspirationFilteredStmt, err = db.PrepareContext(ctx, getPartsForInspirationFiltered); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartsForInspirationFiltered: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSettingsStmt, err = db.PrepareContext(ctx, getSettings); err != nil {
		return nil, fmt.Errorf("error preparing query GetSettings: %w", err)
	}
	if q.getTagByNameStmt, err = db.PrepareContext(ctx, getTagByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagByName: %w", err)
	}
	if q.getTagsForPartStmt, err = db.PrepareContext(ctx, getTagsForPart); err != nil {
		return nil, fmt.Errorf("error preparing query GetTagsForPart: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getWallStmt, err = db.PrepareContext(ctx, getWall); err != nil {
		return nil, fmt.Errorf("error preparing query GetWall: %w", err)
	}
	if q.getWallCardsStmt, err = db.PrepareContext(ctx, getWallCards); err != nil {
		return nil, fmt.Errorf("error preparing query GetWallCards: %w", err)
	}
	if q.getWallContainerBinsStmt, err = db.PrepareContext(ctx, getWallContainerBins); err != nil {
		return nil, fmt.Errorf("error preparing query GetWallContainerBins: %w", err)
	}
	if q.getWallsStmt, err = db.PrepareContext(ctx, getWalls); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalls: %w", err)
	}
	if q.initSettingsStmt, err = db.PrepareContext(ctx, initSettings); err != nil {
		return nil, fmt.Errorf("error preparing query InitSettings: %w", err)
	}
	if q.listAllTagsStmt, err = db.PrepareContext(ctx, listAllTags); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllTags: %w", err)
	}
	if q.listAuditLogsStmt, err = db.PrepareContext(ctx, listAuditLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuditLogs: %w", err)
	}
	if q.listPartsStmt, err = db.PrepareContext(ctx, listParts); err != nil {
		return nil, fmt.Errorf("error preparing query ListParts: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.markInspirationSeedsAppliedStmt, err = db.PrepareContext(ctx, markInspirationSeedsApplied); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInspirationSeedsApplied: %w", err)
	}
	if q.reassignPartAssignmentStmt, err = db.PrepareContext(ctx, reassignPartAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query ReassignPartAssignment: %w", err)
	}
	if q.removeContainerFromWallStmt, err = db.PrepareContext(ctx, removeContainerFromWall); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveContainerFromWall: %w", err)
	}
	if q.removeTagsFromPartStmt, err = db.PrepareContext(ctx, removeTagsFromPart); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTagsFromPart: %w", err)
	}
	if q.restoreAuditLogStmt, err = db.PrepareContext(ctx, restoreAuditLog); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreAuditLog: %w", err)
	}
	if q.restoreBinStmt, err = db.PrepareContext(ctx, restoreBin); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreBin: %w", err)
	}
	if q.restoreContainerStmt, err = db.PrepareContext(ctx, restoreContainer); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreContainer: %w", err)
	}
	if q.restoreControllerStmt, err = db.PrepareContext(ctx, restoreController); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreController: %w", err)
	}
	if q.restorePartStmt, err = db.PrepareContext(ctx, restorePart); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePart: %w", err)
	}
	if q.restorePartAiPromptStmt, err = db.PrepareContext(ctx, restorePartAiPrompt); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePartAiPrompt: %w", err)
	}
	if q.restorePartAssignmentStmt, err = db.PrepareContext(ctx, restorePartAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePartAssignment: %w", err)
	}
	if q.restorePartDocStmt, err = db.PrepareContext(ctx, restorePartDoc); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePartDoc: %w", err)
	}
	if q.restorePartLinkStmt, err = db.PrepareContext(ctx, restorePartLink); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePartLink: %w", err)
	}
	if q.restorePartTagStmt, err = db.PrepareContext(ctx, restorePartTag); err != nil {
		return nil, fmt.Errorf("error preparing query RestorePartTag: %w", err)
	}
	if q.restoreSettingsStmt, err = db.PrepareContext(ctx, restoreSettings); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreSettings: %w", err)
	}
	if q.restoreTagStmt, err = db.PrepareContext(ctx, restoreTag); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreTag: %w", err)
	}
	if q.restoreUserStmt, err = db.PrepareContext(ctx, restoreUser); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreUser: %w", err)
	}
	if q.restoreWallStmt, err = db.PrepareContext(ctx, restoreWall); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreWall: %w", err)
	}
	if q.restoreWallCardStmt, err = db.PrepareContext(ctx, restoreWallCard); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreWallCard: %w", err)
	}
	if q.searchPartsStmt, err = db.PrepareContext(ctx, searchParts); err != nil {
		return nil, fmt.Errorf("error preparing query SearchParts: %w", err)
	}
	if q.setFlagStmt, err = db.PrepareContext(ctx, setFlag); err != nil {
		return nil, fmt.Errorf("error preparing query SetFlag: %w", err)
	}
	if q.setPasswordResetFlagStmt, err = db.PrepareContext(ctx, setPasswordResetFlag); err != nil {
		return nil, fmt.Errorf("error preparing query SetPasswordResetFlag: %w", err)
	}
	if q.updateBinStmt, err = db.PrepareContext(ctx, updateBin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBin: %w", err)
	}
	if q.updateBinLedIndexStmt, err = db.PrepareContext(ctx, updateBinLedIndex); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBinLedIndex: %w", err)
	}
	if q.updateColorsStmt, err = db.PrepareContext(ctx, updateColors); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateColors: %w", err)
	}
	if q.updateContainerConfigStmt, err = db.PrepareContext(ctx, updateContainerConfig); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateContainerConfig: %w", err)
	}
	if q.updateControllerStatusStmt, err = db.PrepareContext(ctx, updateControllerStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateControllerStatus: %w", err)
	}
	if q.updateGeneralSettingsStmt, err = db.PrepareContext(ctx, updateGeneralSettings); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGeneralSettings: %w", err)
	}
	if q.updateInspirationTemplateStmt, err = db.PrepareContext(ctx, updateInspirationTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateInspirationTemplate: %w", err)
	}
	if q.updatePartStmt, err = db.PrepareContext(ctx, updatePart); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePart: %w", err)
	}
	if q.updatePartAssignmentQuantityStmt, err = db.PrepareContext(ctx, updatePartAssignmentQuantity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePartAssignmentQuantity: %w", err)
	}
	if q.updatePartLinkStmt, err = db.PrepareContext(ctx, updatePartLink); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePartLink: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateWallStmt, err = db.PrepareContext(ctx, updateWall); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWall: %w", err)
	}
	if q.updateWallCardPositionStmt, err = db.PrepareContext(ctx, updateWallCardPosition); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWallCardPosition: %w", err)
	}
	if q.upsertBinStmt, err = db.PrepareContext(ctx, upsertBin); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBin: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addContainerToWallStmt != nil {
		if cerr := q.addContainerToWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addContainerToWallStmt: %w", cerr)
		}
	}
	if q.addTagToPartStmt != nil {
		if cerr := q.addTagToPartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTagToPartStmt: %w", cerr)
		}
	}
	if q.cleanupSessionsStmt != nil {
		if cerr := q.cleanupSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cleanupSessionsStmt: %w", cerr)
		}
	}
	if q.clearAuditLogsStmt != nil {
		if cerr := q.clearAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearAuditLogsStmt: %w", cerr)
		}
	}
	if q.clearBinsStmt != nil {
		if cerr := q.clearBinsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearBinsStmt: %w", cerr)
		}
	}
	if q.clearContainerBinLedIndicesStmt != nil {
		if cerr := q.clearContainerBinLedIndicesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearContainerBinLedIndicesStmt: %w", cerr)
		}
	}
	if q.clearContainersStmt != nil {
		if cerr := q.clearContainersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearContainersStmt: %w", cerr)
		}
	}
	if q.clearControllersStmt != nil {
		if cerr := q.clearControllersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearControllersStmt: %w", cerr)
		}
	}
	if q.clearPartAiPromptsStmt != nil {
		if cerr := q.clearPartAiPromptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartAiPromptsStmt: %w", cerr)
		}
	}
	if q.clearPartAssignmentsStmt != nil {
		if cerr := q.clearPartAssignmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartAssignmentsStmt: %w", cerr)
		}
	}
	if q.clearPartDocsStmt != nil {
		if cerr := q.clearPartDocsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartDocsStmt: %w", cerr)
		}
	}
	if q.clearPartLinksStmt != nil {
		if cerr := q.clearPartLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartLinksStmt: %w", cerr)
		}
	}
	if q.clearPartTagsStmt != nil {
		if cerr := q.clearPartTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartTagsStmt: %w", cerr)
		}
	}
	if q.clearPartsStmt != nil {
		if cerr := q.clearPartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearPartsStmt: %w", cerr)
		}
	}
	if q.clearTagsStmt != nil {
		if cerr := q.clearTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearTagsStmt: %w", cerr)
		}
	}
	if q.clearUsersStmt != nil {
		if cerr := q.clearUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearUsersStmt: %w", cerr)
		}
	}
	if q.clearWallCardsStmt != nil {
		if cerr := q.clearWallCardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearWallCardsStmt: %w", cerr)
		}
	}
	if q.clearWallsStmt != nil {
		if cerr := q.clearWallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearWallsStmt: %w", cerr)
		}
	}
	if q.countAuditLogsStmt != nil {
		if cerr := q.countAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAuditLogsStmt: %w", cerr)
		}
	}
	if q.countUsersStmt != nil {
		if cerr := q.countUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUsersStmt: %w", cerr)
		}
	}
	if q.createAuditLogStmt != nil {
		if cerr := q.createAuditLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuditLogStmt: %w", cerr)
		}
	}
	if q.createBinStmt != nil {
		if cerr := q.createBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBinStmt: %w", cerr)
		}
	}
	if q.createContainerStmt != nil {
		if cerr := q.createContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContainerStmt: %w", cerr)
		}
	}
	if q.createControllerStmt != nil {
		if cerr := q.createControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createControllerStmt: %w", cerr)
		}
	}
	if q.createInspirationTemplateStmt != nil {
		if cerr := q.createInspirationTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInspirationTemplateStmt: %w", cerr)
		}
	}
	if q.createPartStmt != nil {
		if cerr := q.createPartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPartStmt: %w", cerr)
		}
	}
	if q.createPartAssignmentStmt != nil {
		if cerr := q.createPartAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPartAssignmentStmt: %w", cerr)
		}
	}
	if q.createPartDocStmt != nil {
		if cerr := q.createPartDocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPartDocStmt: %w", cerr)
		}
	}
	if q.createPartLinkStmt != nil {
		if cerr := q.createPartLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPartLinkStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createTagStmt != nil {
		if cerr := q.createTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTagStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createWallStmt != nil {
		if cerr := q.createWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWallStmt: %w", cerr)
		}
	}
	if q.deleteAssignmentStmt != nil {
		if cerr := q.deleteAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAssignmentStmt: %w", cerr)
		}
	}
	if q.deleteBinStmt != nil {
		if cerr := q.deleteBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBinStmt: %w", cerr)
		}
	}
	if q.deleteBinByLedStmt != nil {
		if cerr := q.deleteBinByLedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBinByLedStmt: %w", cerr)
		}
	}
	if q.deleteBinsByContainerStmt != nil {
		if cerr := q.deleteBinsByContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBinsByContainerStmt: %w", cerr)
		}
	}
	if q.deleteContainerStmt != nil {
		if cerr := q.deleteContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteContainerStmt: %w", cerr)
		}
	}
	if q.deleteControllerStmt != nil {
		if cerr := q.deleteControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteControllerStmt: %w", cerr)
		}
	}
	if q.deleteInspirationTemplateStmt != nil {
		if cerr := q.deleteInspirationTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInspirationTemplateStmt: %w", cerr)
		}
	}
	if q.deletePartStmt != nil {
		if cerr := q.deletePartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePartStmt: %w", cerr)
		}
	}
	if q.deletePartAssignmentStmt != nil {
		if cerr := q.deletePartAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePartAssignmentStmt: %w", cerr)
		}
	}
	if q.deletePartDocStmt != nil {
		if cerr := q.deletePartDocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePartDocStmt: %w", cerr)
		}
	}
	if q.deletePartLinkStmt != nil {
		if cerr := q.deletePartLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePartLinkStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteUnusedTagsStmt != nil {
		if cerr := q.deleteUnusedTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUnusedTagsStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteWallStmt != nil {
		if cerr := q.deleteWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWallStmt: %w", cerr)
		}
	}
	if q.deleteWallCardsByWallIDStmt != nil {
		if cerr := q.deleteWallCardsByWallIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWallCardsByWallIDStmt: %w", cerr)
		}
	}
	if q.getAllAuditLogsStmt != nil {
		if cerr := q.getAllAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllAuditLogsStmt: %w", cerr)
		}
	}
	if q.getAllBinsStmt != nil {
		if cerr := q.getAllBinsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllBinsStmt: %w", cerr)
		}
	}
	if q.getAllContainersStmt != nil {
		if cerr := q.getAllContainersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllContainersStmt: %w", cerr)
		}
	}
	if q.getAllInspirationTemplatesStmt != nil {
		if cerr := q.getAllInspirationTemplatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllInspirationTemplatesStmt: %w", cerr)
		}
	}
	if q.getAllPartAiPromptsStmt != nil {
		if cerr := q.getAllPartAiPromptsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartAiPromptsStmt: %w", cerr)
		}
	}
	if q.getAllPartAssignmentsStmt != nil {
		if cerr := q.getAllPartAssignmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartAssignmentsStmt: %w", cerr)
		}
	}
	if q.getAllPartDocsStmt != nil {
		if cerr := q.getAllPartDocsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartDocsStmt: %w", cerr)
		}
	}
	if q.getAllPartLinksStmt != nil {
		if cerr := q.getAllPartLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartLinksStmt: %w", cerr)
		}
	}
	if q.getAllPartTagsStmt != nil {
		if cerr := q.getAllPartTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartTagsStmt: %w", cerr)
		}
	}
	if q.getAllPartsStmt != nil {
		if cerr := q.getAllPartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartsStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getAllWallCardsStmt != nil {
		if cerr := q.getAllWallCardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllWallCardsStmt: %w", cerr)
		}
	}
	if q.getAllWallContainerBinsStmt != nil {
		if cerr := q.getAllWallContainerBinsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllWallContainerBinsStmt: %w", cerr)
		}
	}
	if q.getAssignmentStmt != nil {
		if cerr := q.getAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignmentStmt: %w", cerr)
		}
	}
	if q.getAssignmentIDStmt != nil {
		if cerr := q.getAssignmentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignmentIDStmt: %w", cerr)
		}
	}
	if q.getBinStmt != nil {
		if cerr := q.getBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBinStmt: %w", cerr)
		}
	}
	if q.getBinByLocationStmt != nil {
		if cerr := q.getBinByLocationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBinByLocationStmt: %w", cerr)
		}
	}
	if q.getBinsByContainerStmt != nil {
		if cerr := q.getBinsByContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBinsByContainerStmt: %w", cerr)
		}
	}
	if q.getContainerStmt != nil {
		if cerr := q.getContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContainerStmt: %w", cerr)
		}
	}
	if q.getContainersByControllerStmt != nil {
		if cerr := q.getContainersByControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getContainersByControllerStmt: %w", cerr)
		}
	}
	if q.getControllerStmt != nil {
		if cerr := q.getControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getControllerStmt: %w", cerr)
		}
	}
	if q.getControllersStmt != nil {
		if cerr := q.getControllersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getControllersStmt: %w", cerr)
		}
	}
	if q.getDashboardGridStmt != nil {
		if cerr := q.getDashboardGridStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDashboardGridStmt: %w", cerr)
		}
	}
	if q.getDashboardGridByControllerStmt != nil {
		if cerr := q.getDashboardGridByControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDashboardGridByControllerStmt: %w", cerr)
		}
	}
	if q.getDashboardStatsStmt != nil {
		if cerr := q.getDashboardStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDashboardStatsStmt: %w", cerr)
		}
	}
	if q.getFlagStmt != nil {
		if cerr := q.getFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFlagStmt: %w", cerr)
		}
	}
	if q.getInspirationTemplateStmt != nil {
		if cerr := q.getInspirationTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInspirationTemplateStmt: %w", cerr)
		}
	}
	if q.getPartStmt != nil {
		if cerr := q.getPartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartStmt: %w", cerr)
		}
	}
	if q.getPartAssignmentsStmt != nil {
		if cerr := q.getPartAssignmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartAssignmentsStmt: %w", cerr)
		}
	}
	if q.getPartDocStmt != nil {
		if cerr := q.getPartDocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartDocStmt: %w", cerr)
		}
	}
	if q.getPartDocsStmt != nil {
		if cerr := q.getPartDocsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartDocsStmt: %w", cerr)
		}
	}
	if q.getPartLinksStmt != nil {
		if cerr := q.getPartLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartLinksStmt: %w", cerr)
		}
	}
	if q.getPartsForInspirationAllStmt != nil {
		if cerr := q.getPartsForInspirationAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartsForInspirationAllStmt: %w", cerr)
		}
	}
	if q.getPartsForInspirationFilteredStmt != nil {
		if cerr := q.getPartsForInspirationFilteredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartsForInspirationFilteredStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSettingsStmt != nil {
		if cerr := q.getSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSettingsStmt: %w", cerr)
		}
	}
	if q.getTagByNameStmt != nil {
		if cerr := q.getTagByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagByNameStmt: %w", cerr)
		}
	}
	if q.getTagsForPartStmt != nil {
		if cerr := q.getTagsForPartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTagsForPartStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getWallStmt != nil {
		if cerr := q.getWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWallStmt: %w", cerr)
		}
	}
	if q.getWallCardsStmt != nil {
		if cerr := q.getWallCardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWallCardsStmt: %w", cerr)
		}
	}
	if q.getWallContainerBinsStmt != nil {
		if cerr := q.getWallContainerBinsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWallContainerBinsStmt: %w", cerr)
		}
	}
	if q.getWallsStmt != nil {
		if cerr := q.getWallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWallsStmt: %w", cerr)
		}
	}
	if q.initSettingsStmt != nil {
		if cerr := q.initSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing initSettingsStmt: %w", cerr)
		}
	}
	if q.listAllTagsStmt != nil {
		if cerr := q.listAllTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllTagsStmt: %w", cerr)
		}
	}
	if q.listAuditLogsStmt != nil {
		if cerr := q.listAuditLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuditLogsStmt: %w", cerr)
		}
	}
	if q.listPartsStmt != nil {
		if cerr := q.listPartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPartsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.markInspirationSeedsAppliedStmt != nil {
		if cerr := q.markInspirationSeedsAppliedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInspirationSeedsAppliedStmt: %w", cerr)
		}
	}
	if q.reassignPartAssignmentStmt != nil {
		if cerr := q.reassignPartAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing reassignPartAssignmentStmt: %w", cerr)
		}
	}
	if q.removeContainerFromWallStmt != nil {
		if cerr := q.removeContainerFromWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeContainerFromWallStmt: %w", cerr)
		}
	}
	if q.removeTagsFromPartStmt != nil {
		if cerr := q.removeTagsFromPartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTagsFromPartStmt: %w", cerr)
		}
	}
	if q.restoreAuditLogStmt != nil {
		if cerr := q.restoreAuditLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreAuditLogStmt: %w", cerr)
		}
	}
	if q.restoreBinStmt != nil {
		if cerr := q.restoreBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreBinStmt: %w", cerr)
		}
	}
	if q.restoreContainerStmt != nil {
		if cerr := q.restoreContainerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreContainerStmt: %w", cerr)
		}
	}
	if q.restoreControllerStmt != nil {
		if cerr := q.restoreControllerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreControllerStmt: %w", cerr)
		}
	}
	if q.restorePartStmt != nil {
		if cerr := q.restorePartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartStmt: %w", cerr)
		}
	}
	if q.restorePartAiPromptStmt != nil {
		if cerr := q.restorePartAiPromptStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartAiPromptStmt: %w", cerr)
		}
	}
	if q.restorePartAssignmentStmt != nil {
		if cerr := q.restorePartAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartAssignmentStmt: %w", cerr)
		}
	}
	if q.restorePartDocStmt != nil {
		if cerr := q.restorePartDocStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartDocStmt: %w", cerr)
		}
	}
	if q.restorePartLinkStmt != nil {
		if cerr := q.restorePartLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartLinkStmt: %w", cerr)
		}
	}
	if q.restorePartTagStmt != nil {
		if cerr := q.restorePartTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restorePartTagStmt: %w", cerr)
		}
	}
	if q.restoreSettingsStmt != nil {
		if cerr := q.restoreSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreSettingsStmt: %w", cerr)
		}
	}
	if q.restoreTagStmt != nil {
		if cerr := q.restoreTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreTagStmt: %w", cerr)
		}
	}
	if q.restoreUserStmt != nil {
		if cerr := q.restoreUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreUserStmt: %w", cerr)
		}
	}
	if q.restoreWallStmt != nil {
		if cerr := q.restoreWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreWallStmt: %w", cerr)
		}
	}
	if q.restoreWallCardStmt != nil {
		if cerr := q.restoreWallCardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreWallCardStmt: %w", cerr)
		}
	}
	if q.searchPartsStmt != nil {
		if cerr := q.searchPartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchPartsStmt: %w", cerr)
		}
	}
	if q.setFlagStmt != nil {
		if cerr := q.setFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setFlagStmt: %w", cerr)
		}
	}
	if q.setPasswordResetFlagStmt != nil {
		if cerr := q.setPasswordResetFlagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setPasswordResetFlagStmt: %w", cerr)
		}
	}
	if q.updateBinStmt != nil {
		if cerr := q.updateBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBinStmt: %w", cerr)
		}
	}
	if q.updateBinLedIndexStmt != nil {
		if cerr := q.updateBinLedIndexStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBinLedIndexStmt: %w", cerr)
		}
	}
	if q.updateColorsStmt != nil {
		if cerr := q.updateColorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateColorsStmt: %w", cerr)
		}
	}
	if q.updateContainerConfigStmt != nil {
		if cerr := q.updateContainerConfigStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateContainerConfigStmt: %w", cerr)
		}
	}
	if q.updateControllerStatusStmt != nil {
		if cerr := q.updateControllerStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateControllerStatusStmt: %w", cerr)
		}
	}
	if q.updateGeneralSettingsStmt != nil {
		if cerr := q.updateGeneralSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGeneralSettingsStmt: %w", cerr)
		}
	}
	if q.updateInspirationTemplateStmt != nil {
		if cerr := q.updateInspirationTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateInspirationTemplateStmt: %w", cerr)
		}
	}
	if q.updatePartStmt != nil {
		if cerr := q.updatePartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePartStmt: %w", cerr)
		}
	}
	if q.updatePartAssignmentQuantityStmt != nil {
		if cerr := q.updatePartAssignmentQuantityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePartAssignmentQuantityStmt: %w", cerr)
		}
	}
	if q.updatePartLinkStmt != nil {
		if cerr := q.updatePartLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePartLinkStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.updateWallStmt != nil {
		if cerr := q.updateWallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWallStmt: %w", cerr)
		}
	}
	if q.updateWallCardPositionStmt != nil {
		if cerr := q.updateWallCardPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWallCardPositionStmt: %w", cerr)
		}
	}
	if q.upsertBinStmt != nil {
		if cerr := q.upsertBinStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBinStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                 DBTX
	tx                                 *sql.Tx
	addContainerToWallStmt             *sql.Stmt
	addTagToPartStmt                   *sql.Stmt
	cleanupSessionsStmt                *sql.Stmt
	clearAuditLogsStmt                 *sql.Stmt
	clearBinsStmt                      *sql.Stmt
	clearContainerBinLedIndicesStmt    *sql.Stmt
	clearContainersStmt                *sql.Stmt
	clearControllersStmt               *sql.Stmt
	clearPartAiPromptsStmt             *sql.Stmt
	clearPartAssignmentsStmt           *sql.Stmt
	clearPartDocsStmt                  *sql.Stmt
	clearPartLinksStmt                 *sql.Stmt
	clearPartTagsStmt                  *sql.Stmt
	clearPartsStmt                     *sql.Stmt
	clearTagsStmt                      *sql.Stmt
	clearUsersStmt                     *sql.Stmt
	clearWallCardsStmt                 *sql.Stmt
	clearWallsStmt                     *sql.Stmt
	countAuditLogsStmt                 *sql.Stmt
	countUsersStmt                     *sql.Stmt
	createAuditLogStmt                 *sql.Stmt
	createBinStmt                      *sql.Stmt
	createContainerStmt                *sql.Stmt
	createControllerStmt               *sql.Stmt
	createInspirationTemplateStmt      *sql.Stmt
	createPartStmt                     *sql.Stmt
	createPartAssignmentStmt           *sql.Stmt
	createPartDocStmt                  *sql.Stmt
	createPartLinkStmt                 *sql.Stmt
	createSessionStmt                  *sql.Stmt
	createTagStmt                      *sql.Stmt
	createUserStmt                     *sql.Stmt
	createWallStmt                     *sql.Stmt
	deleteAssignmentStmt               *sql.Stmt
	deleteBinStmt                      *sql.Stmt
	deleteBinByLedStmt                 *sql.Stmt
	deleteBinsByContainerStmt          *sql.Stmt
	deleteContainerStmt                *sql.Stmt
	deleteControllerStmt               *sql.Stmt
	deleteInspirationTemplateStmt      *sql.Stmt
	deletePartStmt                     *sql.Stmt
	deletePartAssignmentStmt           *sql.Stmt
	deletePartDocStmt                  *sql.Stmt
	deletePartLinkStmt                 *sql.Stmt
	deleteSessionStmt                  *sql.Stmt
	deleteUnusedTagsStmt               *sql.Stmt
	deleteUserStmt                     *sql.Stmt
	deleteWallStmt                     *sql.Stmt
	deleteWallCardsByWallIDStmt        *sql.Stmt
	getAllAuditLogsStmt                *sql.Stmt
	getAllBinsStmt                     *sql.Stmt
	getAllContainersStmt               *sql.Stmt
	getAllInspirationTemplatesStmt     *sql.Stmt
	getAllPartAiPromptsStmt            *sql.Stmt
	getAllPartAssignmentsStmt          *sql.Stmt
	getAllPartDocsStmt                 *sql.Stmt
	getAllPartLinksStmt                *sql.Stmt
	getAllPartTagsStmt                 *sql.Stmt
	getAllPartsStmt                    *sql.Stmt
	getAllUsersStmt                    *sql.Stmt
	getAllWallCardsStmt                *sql.Stmt
	getAllWallContainerBinsStmt        *sql.Stmt
	getAssignmentStmt                  *sql.Stmt
	getAssignmentIDStmt                *sql.Stmt
	getBinStmt                         *sql.Stmt
	getBinByLocationStmt               *sql.Stmt
	getBinsByContainerStmt             *sql.Stmt
	getContainerStmt                   *sql.Stmt
	getContainersByControllerStmt      *sql.Stmt
	getControllerStmt                  *sql.Stmt
	getControllersStmt                 *sql.Stmt
	getDashboardGridStmt               *sql.Stmt
	getDashboardGridByControllerStmt   *sql.Stmt
	getDashboardStatsStmt              *sql.Stmt
	getFlagStmt                        *sql.Stmt
	getInspirationTemplateStmt         *sql.Stmt
	getPartStmt                        *sql.Stmt
	getPartAssignmentsStmt             *sql.Stmt
	getPartDocStmt                     *sql.Stmt
	getPartDocsStmt                    *sql.Stmt
	getPartLinksStmt                   *sql.Stmt
	getPartsForInspirationAllStmt      *sql.Stmt
	getPartsForInspirationFilteredStmt *sql.Stmt
	getSessionStmt                     *sql.Stmt
	getSettingsStmt                    *sql.Stmt
	getTagByNameStmt                   *sql.Stmt
	getTagsForPartStmt                 *sql.Stmt
	getUserStmt                        *sql.Stmt
	getUserByEmailStmt                 *sql.Stmt
	getWallStmt                        *sql.Stmt
	getWallCardsStmt                   *sql.Stmt
	getWallContainerBinsStmt           *sql.Stmt
	getWallsStmt                       *sql.Stmt
	initSettingsStmt                   *sql.Stmt
	listAllTagsStmt                    *sql.Stmt
	listAuditLogsStmt                  *sql.Stmt
	listPartsStmt                      *sql.Stmt
	listUsersStmt                      *sql.Stmt
	markInspirationSeedsAppliedStmt    *sql.Stmt
	reassignPartAssignmentStmt         *sql.Stmt
	removeContainerFromWallStmt        *sql.Stmt
	removeTagsFromPartStmt             *sql.Stmt
	restoreAuditLogStmt                *sql.Stmt
	restoreBinStmt                     *sql.Stmt
	restoreContainerStmt               *sql.Stmt
	restoreControllerStmt              *sql.Stmt
	restorePartStmt                    *sql.Stmt
	restorePartAiPromptStmt            *sql.Stmt
	restorePartAssignmentStmt          *sql.Stmt
	restorePartDocStmt                 *sql.Stmt
	restorePartLinkStmt                *sql.Stmt
	restorePartTagStmt                 *sql.Stmt
	restoreSettingsStmt                *sql.Stmt
	restoreTagStmt                     *sql.Stmt
	restoreUserStmt                    *sql.Stmt
	restoreWallStmt                    *sql.Stmt
	restoreWallCardStmt                *sql.Stmt
	searchPartsStmt                    *sql.Stmt
	setFlagStmt                        *sql.Stmt
	setPasswordResetFlagStmt           *sql.Stmt
	updateBinStmt                      *sql.Stmt
	updateBinLedIndexStmt              *sql.Stmt
	updateColorsStmt                   *sql.Stmt
	updateContainerConfigStmt          *sql.Stmt
	updateControllerStatusStmt         *sql.Stmt
	updateGeneralSettingsStmt          *sql.Stmt
	updateInspirationTemplateStmt      *sql.Stmt
	updatePartStmt                     *sql.Stmt
	updatePartAssignmentQuantityStmt   *sql.Stmt
	updatePartLinkStmt                 *sql.Stmt
	updateUserPasswordStmt             *sql.Stmt
	updateWallStmt                     *sql.Stmt
	updateWallCardPositionStmt         *sql.Stmt
	upsertBinStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		addContainerToWallStmt:             q.addContainerToWallStmt,
		addTagToPartStmt:                   q.addTagToPartStmt,
		cleanupSessionsStmt:                q.cleanupSessionsStmt,
		clearAuditLogsStmt:                 q.clearAuditLogsStmt,
		clearBinsStmt:                      q.clearBinsStmt,
		clearContainerBinLedIndicesStmt:    q.clearContainerBinLedIndicesStmt,
		clearContainersStmt:                q.clearContainersStmt,
		clearControllersStmt:               q.clearControllersStmt,
		clearPartAiPromptsStmt:             q.clearPartAiPromptsStmt,
		clearPartAssignmentsStmt:           q.clearPartAssignmentsStmt,
		clearPartDocsStmt:                  q.clearPartDocsStmt,
		clearPartLinksStmt:                 q.clearPartLinksStmt,
		clearPartTagsStmt:                  q.clearPartTagsStmt,
		clearPartsStmt:                     q.clearPartsStmt,
		clearTagsStmt:                      q.clearTagsStmt,
		clearUsersStmt:                     q.clearUsersStmt,
		clearWallCardsStmt:                 q.clearWallCardsStmt,
		clearWallsStmt:                     q.clearWallsStmt,
		countAuditLogsStmt:                 q.countAuditLogsStmt,
		countUsersStmt:                     q.countUsersStmt,
		createAuditLogStmt:                 q.createAuditLogStmt,
		createBinStmt:                      q.createBinStmt,
		createContainerStmt:                q.createContainerStmt,
		createControllerStmt:               q.createControllerStmt,
		createInspirationTemplateStmt:      q.createInspirationTemplateStmt,
		createPartStmt:                     q.createPartStmt,
		createPartAssignmentStmt:           q.createPartAssignmentStmt,
		createPartDocStmt:                  q.createPartDocStmt,
		createPartLinkStmt:                 q.createPartLinkStmt,
		createSessionStmt:                  q.createSessionStmt,
		createTagStmt:                      q.createTagStmt,
		createUserStmt:                     q.createUserStmt,
		createWallStmt:                     q.createWallStmt,
		deleteAssignmentStmt:               q.deleteAssignmentStmt,
		deleteBinStmt:                      q.deleteBinStmt,
		deleteBinByLedStmt:                 q.deleteBinByLedStmt,
		deleteBinsByContainerStmt:          q.deleteBinsByContainerStmt,
		deleteContainerStmt:                q.deleteContainerStmt,
		deleteControllerStmt:               q.deleteControllerStmt,
		deleteInspirationTemplateStmt:      q.deleteInspirationTemplateStmt,
		deletePartStmt:                     q.deletePartStmt,
		deletePartAssignmentStmt:           q.deletePartAssignmentStmt,
		deletePartDocStmt:                  q.deletePartDocStmt,
		deletePartLinkStmt:                 q.deletePartLinkStmt,
		deleteSessionStmt:                  q.deleteSessionStmt,
		deleteUnusedTagsStmt:               q.deleteUnusedTagsStmt,
		deleteUserStmt:                     q.deleteUserStmt,
		deleteWallStmt:                     q.deleteWallStmt,
		deleteWallCardsByWallIDStmt:        q.deleteWallCardsByWallIDStmt,
		getAllAuditLogsStmt:                q.getAllAuditLogsStmt,
		getAllBinsStmt:                     q.getAllBinsStmt,
		getAllContainersStmt:               q.getAllContainersStmt,
		getAllInspirationTemplatesStmt:     q.getAllInspirationTemplatesStmt,
		getAllPartAiPromptsStmt:            q.getAllPartAiPromptsStmt,
		getAllPartAssignmentsStmt:          q.getAllPartAssignmentsStmt,
		getAllPartDocsStmt:                 q.getAllPartDocsStmt,
		getAllPartLinksStmt:                q.getAllPartLinksStmt,
		getAllPartTagsStmt:                 q.getAllPartTagsStmt,
		getAllPartsStmt:                    q.getAllPartsStmt,
		getAllUsersStmt:                    q.getAllUsersStmt,
		getAllWallCardsStmt:                q.getAllWallCardsStmt,
		getAllWallContainerBinsStmt:        q.getAllWallContainerBinsStmt,
		getAssignmentStmt:                  q.getAssignmentStmt,
		getAssignmentIDStmt:                q.getAssignmentIDStmt,
		getBinStmt:                         q.getBinStmt,
		getBinByLocationStmt:               q.getBinByLocationStmt,
		getBinsByContainerStmt:             q.getBinsByContainerStmt,
		getContainerStmt:                   q.getContainerStmt,
		getContainersByControllerStmt:      q.getContainersByControllerStmt,
		getControllerStmt:                  q.getControllerStmt,
		getControllersStmt:                 q.getControllersStmt,
		getDashboardGridStmt:               q.getDashboardGridStmt,
		getDashboardGridByControllerStmt:   q.getDashboardGridByControllerStmt,
		getDashboardStatsStmt:              q.getDashboardStatsStmt,
		getFlagStmt:                        q.getFlagStmt,
		getInspirationTemplateStmt:         q.getInspirationTemplateStmt,
		getPartStmt:                        q.getPartStmt,
		getPartAssignmentsStmt:             q.getPartAssignmentsStmt,
		getPartDocStmt:                     q.getPartDocStmt,
		getPartDocsStmt:                    q.getPartDocsStmt,
		getPartLinksStmt:                   q.getPartLinksStmt,
		getPartsForInspirationAllStmt:      q.getPartsForInspirationAllStmt,
		getPartsForInspirationFilteredStmt: q.getPartsForInspirationFilteredStmt,
		getSessionStmt:                     q.getSessionStmt,
		getSettingsStmt:                    q.getSettingsStmt,
		getTagByNameStmt:                   q.getTagByNameStmt,
		getTagsForPartStmt:                 q.getTagsForPartStmt,
		getUserStmt:                        q.getUserStmt,
		getUserByEmailStmt:                 q.getUserByEmailStmt,
		getWallStmt:                        q.getWallStmt,
		getWallCardsStmt:                   q.getWallCardsStmt,
		getWallContainerBinsStmt:           q.getWallContainerBinsStmt,
		getWallsStmt:                       q.getWallsStmt,
		initSettingsStmt:                   q.initSettingsStmt,
		listAllTagsStmt:                    q.listAllTagsStmt,
		listAuditLogsStmt:                  q.listAuditLogsStmt,
		listPartsStmt:                      q.listPartsStmt,
		listUsersStmt:                      q.listUsersStmt,
		markInspirationSeedsAppliedStmt:    q.markInspirationSeedsAppliedStmt,
		reassignPartAssignmentStmt:         q.reassignPartAssignmentStmt,
		removeContainerFromWallStmt:        q.removeContainerFromWallStmt,
		removeTagsFromPartStmt:             q.removeTagsFromPartStmt,
		restoreAuditLogStmt:                q.restoreAuditLogStmt,
		restoreBinStmt:                     q.restoreBinStmt,
		restoreContainerStmt:               q.restoreContainerStmt,
		restoreControllerStmt:              q.restoreControllerStmt,
		restorePartStmt:                    q.restorePartStmt,
		restorePartAiPromptStmt:            q.restorePartAiPromptStmt,
		restorePartAssignmentStmt:          q.restorePartAssignmentStmt,
		restorePartDocStmt:                 q.restorePartDocStmt,
		restorePartLinkStmt:                q.restorePartLinkStmt,
		restorePartTagStmt:                 q.restorePartTagStmt,
		restoreSettingsStmt:                q.restoreSettingsStmt,
		restoreTagStmt:                     q.restoreTagStmt,
		restoreUserStmt:                    q.restoreUserStmt,
		restoreWallStmt:                    q.restoreWallStmt,
		restoreWallCardStmt:                q.restoreWallCardStmt,
		searchPartsStmt:                    q.searchPartsStmt,
		setFlagStmt:                        q.setFlagStmt,
		setPasswordResetFlagStmt:           q.setPasswordResetFlagStmt,
		updateBinStmt:                      q.updateBinStmt,
		updateBinLedIndexStmt:              q.updateBinLedIndexStmt,
		updateColorsStmt:                   q.updateColorsStmt,
		updateContainerConfigStmt:          q.updateContainerConfigStmt,
		updateControllerStatusStmt:         q.updateControllerStatusStmt,
		updateGeneralSettingsStmt:          q.updateGeneralSettingsStmt,
		updateInspirationTemplateStmt:      q.updateInspirationTemplateStmt,
		updatePartStmt:                     q.updatePartStmt,
		updatePartAssignmentQuantityStmt:   q.updatePartAssignmentQuantityStmt,
		updatePartLinkStmt:                 q.updatePartLinkStmt,
		updateUserPasswordStmt:             q.updateUserPasswordStmt,
		updateWallStmt:                     q.updateWallStmt,
		updateWallCardPositionStmt:         q.updateWallCardPositionStmt,
		upsertBinStmt:                      q.upsertBinStmt,
	}
}
