// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddContainerToWall(ctx context.Context, arg AddContainerToWallParams) error
	AddTagToPart(ctx context.Context, arg AddTagToPartParams) error
	CleanupSessions(ctx context.Context, expiry float64) error
	ClearAuditLogs(ctx context.Context) error
	ClearBins(ctx context.Context) error
	ClearContainerBinLedIndices(ctx context.Context, containerID int64) error
	ClearContainers(ctx context.Context) error
	ClearControllers(ctx context.Context) error
	ClearPartAiPrompts(ctx context.Context) error
	ClearPartAssignments(ctx context.Context) error
	ClearPartDocs(ctx context.Context) error
	ClearPartLinks(ctx context.Context) error
	ClearPartTags(ctx context.Context) error
	ClearParts(ctx context.Context) error
	ClearTags(ctx context.Context) error
	ClearUsers(ctx context.Context) error
	ClearWallCards(ctx context.Context) error
	ClearWalls(ctx context.Context) error
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateBin(ctx context.Context, arg CreateBinParams) (int64, error)
	CreateContainer(ctx context.Context, arg CreateContainerParams) (int64, error)
	CreateController(ctx context.Context, arg CreateControllerParams) (CreateControllerRow, error)
	CreateInspirationTemplate(ctx context.Context, arg CreateInspirationTemplateParams) (InspirationTemplate, error)
	CreatePart(ctx context.Context, arg CreatePartParams) (int64, error)
	CreatePartAssignment(ctx context.Context, arg CreatePartAssignmentParams) error
	// DOCUMENTS
	CreatePartDoc(ctx context.Context, arg CreatePartDocParams) error
	// LINKS
	CreatePartLink(ctx context.Context, arg CreatePartLinkParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWall(ctx context.Context, arg CreateWallParams) (int64, error)
	DeleteAssignment(ctx context.Context, id int64) error
	DeleteBin(ctx context.Context, id int64) error
	DeleteBinByLed(ctx context.Context, arg DeleteBinByLedParams) error
	DeleteBinsByContainer(ctx context.Context, containerID int64) error
	DeleteContainer(ctx context.Context, id int64) error
	DeleteController(ctx context.Context, id int64) error
	DeleteInspirationTemplate(ctx context.Context, id int64) error
	DeletePart(ctx context.Context, id int64) error
	DeletePartAssignment(ctx context.Context, arg DeletePartAssignmentParams) error
	DeletePartDoc(ctx context.Context, id int64) error
	DeletePartLink(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUnusedTags(ctx context.Context) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWall(ctx context.Context, id int64) error
	DeleteWallCardsByWallID(ctx context.Context, wallID int64) error
	GetAllAuditLogs(ctx context.Context) ([]GetAllAuditLogsRow, error)
	GetAllBins(ctx context.Context) ([]Bin, error)
	GetAllContainers(ctx context.Context) ([]Container, error)
	GetAllInspirationTemplates(ctx context.Context) ([]InspirationTemplate, error)
	GetAllPartAiPrompts(ctx context.Context) ([]PartAiPrompt, error)
	// STOCK ASSIGNMENTS
	GetAllPartAssignments(ctx context.Context) ([]PartAssignment, error)
	GetAllPartDocs(ctx context.Context) ([]PartDoc, error)
	GetAllPartLinks(ctx context.Context) ([]PartLink, error)
	GetAllPartTags(ctx context.Context) ([]PartTag, error)
	GetAllParts(ctx context.Context) ([]Part, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAllWallCards(ctx context.Context) ([]WallCard, error)
	GetAllWallContainerBins(ctx context.Context) ([]GetAllWallContainerBinsRow, error)
	GetAssignment(ctx context.Context, id int64) (PartAssignment, error)
	GetAssignmentID(ctx context.Context, arg GetAssignmentIDParams) (int64, error)
	GetBin(ctx context.Context, id int64) (Bin, error)
	GetBinByLocation(ctx context.Context, arg GetBinByLocationParams) (int64, error)
	GetBinsByContainer(ctx context.Context, containerID int64) ([]Bin, error)
	GetContainer(ctx context.Context, id int64) (Container, error)
	GetContainersByController(ctx context.Context, controllerID int64) ([]Container, error)
	GetController(ctx context.Context, id int64) (Controller, error)
	GetControllers(ctx context.Context) ([]Controller, error)
	GetDashboardGrid(ctx context.Context) ([]GetDashboardGridRow, error)
	GetDashboardGridByController(ctx context.Context, id int64) ([]GetDashboardGridByControllerRow, error)
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetFlag(ctx context.Context, key string) (string, error)
	GetInspirationTemplate(ctx context.Context, id int64) (InspirationTemplate, error)
	GetPart(ctx context.Context, id int64) (Part, error)
	GetPartAssignments(ctx context.Context, partID int64) ([]GetPartAssignmentsRow, error)
	GetPartDoc(ctx context.Context, id int64) (PartDoc, error)
	GetPartDocs(ctx context.Context, partID int64) ([]PartDoc, error)
	GetPartLinks(ctx context.Context, partID int64) ([]PartLink, error)
	GetPartsForInspirationAll(ctx context.Context) ([]GetPartsForInspirationAllRow, error)
	GetPartsForInspirationFiltered(ctx context.Context, tags []string) ([]GetPartsForInspirationFilteredRow, error)
	// SESSION QUERIES
	GetSession(ctx context.Context, token string) (Session, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTagsForPart(ctx context.Context, partID int64) ([]Tag, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWall(ctx context.Context, id int64) (Wall, error)
	GetWallCards(ctx context.Context, wallID int64) ([]GetWallCardsRow, error)
	GetWallContainerBins(ctx context.Context, wallID int64) ([]GetWallContainerBinsRow, error)
	GetWalls(ctx context.Context) ([]Wall, error)
	InitSettings(ctx context.Context) error
	ListAllTags(ctx context.Context) ([]Tag, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListParts(ctx context.Context, arg ListPartsParams) ([]ListPartsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkInspirationSeedsApplied(ctx context.Context) error
	ReassignPartAssignment(ctx context.Context, arg ReassignPartAssignmentParams) error
	RemoveContainerFromWall(ctx context.Context, arg RemoveContainerFromWallParams) error
	RemoveTagsFromPart(ctx context.Context, partID int64) error
	RestoreAuditLog(ctx context.Context, arg RestoreAuditLogParams) error
	RestoreBin(ctx context.Context, arg RestoreBinParams) error
	RestoreContainer(ctx context.Context, arg RestoreContainerParams) error
	RestoreController(ctx context.Context, arg RestoreControllerParams) error
	RestorePart(ctx context.Context, arg RestorePartParams) error
	RestorePartAiPrompt(ctx context.Context, arg RestorePartAiPromptParams) error
	RestorePartAssignment(ctx context.Context, arg RestorePartAssignmentParams) error
	RestorePartDoc(ctx context.Context, arg RestorePartDocParams) error
	RestorePartLink(ctx context.Context, arg RestorePartLinkParams) error
	RestorePartTag(ctx context.Context, arg RestorePartTagParams) error
	RestoreSettings(ctx context.Context, arg RestoreSettingsParams) error
	RestoreTag(ctx context.Context, arg RestoreTagParams) error
	RestoreUser(ctx context.Context, arg RestoreUserParams) error
	RestoreWall(ctx context.Context, arg RestoreWallParams) error
	RestoreWallCard(ctx context.Context, arg RestoreWallCardParams) error
	SearchParts(ctx context.Context, arg SearchPartsParams) ([]SearchPartsRow, error)
	SetFlag(ctx context.Context, arg SetFlagParams) error
	SetPasswordResetFlag(ctx context.Context, arg SetPasswordResetFlagParams) error
	UpdateBin(ctx context.Context, arg UpdateBinParams) error
	UpdateBinLedIndex(ctx context.Context, arg UpdateBinLedIndexParams) error
	UpdateColors(ctx context.Context, arg UpdateColorsParams) error
	UpdateContainerConfig(ctx context.Context, arg UpdateContainerConfigParams) error
	UpdateControllerStatus(ctx context.Context, arg UpdateControllerStatusParams) error
	UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) error
	UpdateInspirationTemplate(ctx context.Context, arg UpdateInspirationTemplateParams) error
	UpdatePart(ctx context.Context, arg UpdatePartParams) error
	UpdatePartAssignmentQuantity(ctx context.Context, arg UpdatePartAssignmentQuantityParams) error
	UpdatePartLink(ctx context.Context, arg UpdatePartLinkParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWall(ctx context.Context, arg UpdateWallParams) error
	UpdateWallCardPosition(ctx context.Context, arg UpdateWallCardPositionParams) error
	UpsertBin(ctx context.Context, arg UpsertBinParams) error
}

var _ Querier = (*Queries)(nil)
